apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: redis-enterprise-operator.v0.0.1
  namespace: placeholder
  annotations:
    capabilities: Basic Install
    categories: "Database"
    certified: "false"
    containerImage: redislabs/operator-internal:562_ee119ea
    createdAt: 2019-02-24T11:35:59Z
    description: An operator to run Redis Enterprise Clusters
    support: Redis Labs
    alm-examples: '[{"apiVersion":"app.redislabs.com/v1alpha1","kind":"RedisEnterpriseCluster","metadata":{"name":"redis-enterprise"},"spec":{"nodes":3,"persistentSpec":{"enabled":"true","storageClassName":"gp2"},"uiServiceType":"LoadBalancer","username":"admin@acme.com","redisEnterpriseNodeResources":{"limits":{"cpu":"400m","memory":"4 Gi"},"requests":{"cpu":"400m","memory":"4 Gi"}},"redisEnterpriseImageSpec":{"imagePullPolicy":"IfNotPresent","repository":"redislabs/redis","versionTag":"5.4.0-19"}}}]'
spec:
  customresourcedefinitions:
    owned:
      - description: Instance of a Redis Enterprise cluster
        displayName: Redis Enterprise Cluster
        group: app.redislabs.com
        kind: RedisEnterpriseCluster
        name: redisenterpriseclusters.app.redislabs.com
        resources:
          - kind: Service
            name: ''
            version: v1
          - kind: StatefulSet
            name: ''
            version: v1beta2
          - kind: Pod
            name: ''
            version: v1
        specDescriptors:
          - description: The ServiceAccount to use to run the Prometheus pods
            displayName: Service Account
            path: serviceAccountName
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:ServiceAccount'
          - description: Storage class configured for persistent storage
            displayName: Storage Class
            path: persistentSpec.storageClassName
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:StorageClass'
          - description: Number of Redis Nodes
            displayName: Redis Nodes
            path: nodes
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:text'
        version: v1alpha1
  keywords:
    - redis
    - database
    - nosql
  displayName: Redis Enterprise
  provider:
    name: 'Redis Labs, Inc'
  maturity: beta
  version: 0.0.1
  icon:
    - base64data: >-
        iVBORw0KGgoAAAANSUhEUgAAAN4AAADjCAMAAADdXVr2AAABCFBMVEXbOCyiIyL///82QlOrJyR0ERMgMEXT1dfY2t2fIiGcAAAqOEvdu7sbLEIxPlDeOSyZnaTw8PHs2dhbY3HZJhWnq7HQNCraMyYlNEf4+PmuKCXWNiueCgjHMSjxwL3aLR66LCaOk5pLVGK7vsPWqalmbnrZHga1KiXZKBhCTV3ZIQz32NZsDRHBLif65+bwuLXIys7okIvle3X98/LeTEL0ysjfUknjb2jso5/lenSwtLmfFRSBh5DurqvhYlqoNzbnh4JvdoHPmprqmJTlycnAeXirPj4FIDkACS0AGDThZV6JGRjeUEaBFhaoAADgW1LHiYmvTEy9c3O4ZWXZsLDKWVXanZvDFQJgbBkIAAATrklEQVR4nO2de0PbOBLA81oDcWOTYnBCCuaxmOCUpCE8AgQaSlvuuuzS7uP2+3+T08PPxJJmlKR3dJk/WkhsSz/NaGY0UkKh9D1l0OkN++Nxf7jdGXyXBgvfpRUqg+3+oxO0PSbtIHjsnzUX3uh3whv0bn3HcwspcT3Hv9hesBK/C17vi9POoMWIjnd5tsiWF493duI7uWwhYeD1OwtrfMF4g+Fp4InZmNief95b0DRcKN7ZhZ9vlFMqbAfjhahwcXjdvh2A2Lh4welw/n5mQXiD3pPv2XA4rkL/Yt5+ZiF4nRNH5k0khEFh2J1nT+aPR7yJr/ImYiF+Zp4qnDceUdyUN/FwtK7j3s9LhXPF6+YqzhuOA6EDdfPeICq83Z5Lj+aIt32bT+E+lZq9pyDH05B48DTOB5+TCueF1713hd4koJro9r3sBcRR3t50S32R5RIVPvVm7dZ88LZvZWHADhvZvnDadqSc9kWPhrlBW3gbvcqZMdrPAa/bFyuOS3sYXjoYtoiRek5wGS0VbmR4RGZU4ax4g945IH47ST7SOSmMU56/pbx3JhXOhtc5aYOSSm8seMBZALibqPD8Rq+DM+ANhgXlaiASX+AFvwCTG+KHtFSojXd2EbThSWX7NvchXZDyuNBl03fC6w4xqwHiJi/zo/QYlc9oqFAHD6U4Gt56opVOC7usIMumG8yyCY1H4jdccSQ0P0qXAJ2xh1xb4FSIxMtPrkRsgQ1IrHrSlCBPyJhBVYjB6/YRyzjX8aCj3L1vYdb1BaZCWIUNjkcVh+gArsBHpzOSMGjdq1UIxOuMsevvpy8n42HvrNMFmtHg5hy5wCcT+4tqDCF4kGredOOu63ltJyBO9vTpss9IJW10O2c3T+gCBi1eSIdPjQeu5glBI1LfP80+ujnonPWG44tz1/eDiRo99OHy4oUCjyZeM7FlxUnyjs7FeYssHZy257muzHPatsKvEhUKHbQUjyoOWc2Ti+3FpnTRlkJFNxS2Dn89LCgI6SzMT4vEeOplnIbES4euD7jabh1XKps/vf1pZUOpQsft56hQhCdff1PPEU4nLgG1MrmRcfHDWKjONqniKhWKR+TtrzsFxcNZ8WLSz+TiTdVFsuK2g/bpF+L2O8TtD6iH6FLHd3/yVFA6CPeJtTBwFH21WzsVLgzvJ6AKg5OOAo8EIIniSKblXNwIt467Z/1HuaMNmHeR1yCI4jYrlSweJfxFqUKSsJ2mk9xJvI6kJskzLWU20r05l4RJ26PXSGoQtr2xU0lJgkdVWFSrsJ0qkmbwBjfS+rnrPwIXlCQ7FT7H68tqEBnFTeEBVeg6heEUXkcRv51zRBrZvBfOXr9bus1/b1JxeXgwFdptr5fBI4mX3Cn4QzFMrgbPBQp0v+TXIOzC8eYUXA4eV6ES0L9M8IbKhN3H79tciPhOp7tmF3IUJ8QLVSjvsXMZ4vVcRTGV0OkUU0U58lS/SPzOU5wED6JCMgso3qWvrqVeatABC2FEcYciNhkeV6HkwUGH4p0oQiwVR29LEVLGlChOiff2l2OJZoLXBA+U/YnKsAoRbv+kZDIQwI1TkWvbv1G8DsSCAr0q/yUkJ8+LBmrX8nZlS+E8N6sU7zUEj8ZivDQBZs8Aw+wZjKdSHHVWlRWO9xtkSefoWCeiCJ2k0Eo8SHJtH68UixyvugNZV3p4vnvEDkJeOpaL9/YX5eqWmHuF0EV4K5vKLI7mcdjN/EugaSa9yp2F2JSawG1SuBivuFLcAijQv8QocLugc7glR4W4BRGBO+RwCV6xuFJRpTgFun8xhgJuPwaaRZopFW4iFJdoLovHAZV3e/4X4W5PIp1+a6YqTTa33gwVB2CztyoJXBaPAqoiSYEuFp3H+zMxYrd34sJ3WcQdTVRIS0kQ2yKDkoGbxCOAxWOIk/Ec//Tivtfppgrsg2737GZ86/ptFJvteoKlSpJl/wLpFAksxSzcNB4BXDkEDBQ9K0UPs9MarN1qEWBabae1MjgaBQucwtP45kK0rrBpqn2sPjvB/ckkXB4eBdwE2GiqD7ayjDxxBxkaJ/ALF/0eq0h1JYsxuwVRnL21mQOXjwe2UQ1hWnYfL4fbqRT2dLZaMZlyU1Ypx4PbKFSYLfvt2/HNWXfiUPi9ciUtk7wpp8ajgJWteajQ9YgjajNPlOtuO5DlmIiNRjkhnBSP2yhkWovappbo+48nw23ZDqa+aU5GOSxeaKNoQpu6jmDjtk8sUZUB9HVNk8QNsVUC8biN4gDdoHApssR5maadHwjweJSwuIOwUfcSdapGa0O2QKxSDQfEY6EQbqOucwkuXOiYptRXauEVcaHQ809hRVG8aQKtMpISFI8Cwt2M63h5W6VTpon0WsxXwuGqHxF4uFAIOXOCOw4oS0/y6V6VWBEeilfEuRk3aEnPnJxhTNO2WxirLBavr1+XON7PCD6Um7Hb/onYzWBWF6KkWSjVTzz3o3sMXzF8uGzGC0Q7nidg08RaJYH79jqa3vSfV9VrHCAim3Gddp6bAZsmzlcyuPev4mb4/t7gD5wCqZtBRIpgys0MYKaJ9JWsZ5U/U+1Eu7Mf3yMBqZsBL5qm3IxoZzMLh7ZKVi8qpM6RJnvrr96/wQJiIkU7feRkG2CaeKsMi2G2F8R5RfpkxH+ukY/DZjPRSf2BstyE95WZJbjruDcTeNu3nmJ5KH4q0s2oTJMkzWirnIjItnPaTeENbVZ5RSSsKUBkNtOTb61o9CHPiFy6J8nxbtrxwUa23EACEkJENiM+0cPax1uQwIu7HsfrnjoZvWpMamz9UMSmLDDkNSyaHD47OtDxpxaVOjY6Y22moBcIVg7FbbKjA6VcNwZeEk80plGbiVps7aCtUuq37b9lRwe0bFS7BIxvTDUd7I2q4mQEpByVA4ipzfB2Zoty+c/cCo8O/C0bAnzSh7ZR0sY8AkH2mYXDlajWIh1sTRsFZ9x4fwKIs3zAolKSIjXW8GjQUKgDpzSNaAc6PjpwrLoBPzkgC3u8WQKCj92KttfjQiDgaIReKJTVuDXg1CXz1MGIdJ2TjrQKUCsUipwA2iwhVZ7MwYhsGRdyt1a6RgOFPeuDAOFmKqObqFJDMn8dN0MrFy3+USe+Vb1B7BwHp+5ZTsemivCQtFEz4y5u7hxvETk+JBaOtEp1GM31DDl7DKCQrJXNkEdzQd4Fscr8Ac/fQgHZqE6k0BBACiteRIl2iEBpo1akwLEB1pAyXyDeAIPZqM7CHgGnPp0hdwPS/T1I2qiXkILgQFYpnyCK7cv/mY1CilMA01HuzoL2g7QWTVI4gFVCBhWy+QyzUXwhQdiefiDQwQOewJo+TakHB0iawS1Bjw6ATrfM7ma00xMR3gC8tw6q8mmte1NwAKtEJBNvPmGODsBCoW42Q6acfnqSK9ef2R5DF76xB6qgaGXc6gdj89zqH+EO0WfEzjOzoHln3OpD+Oh5fV39EG2AdVEb66D9IIyNqusE+OSv+q2bbF92i7h9WWg2AwFUBx18WnT9/mN28xl59AOYzSj9qNpZakSblcpfyTZ+uH35+hv65AAom5GlawA4fPFqpbhVcNvxocR48/kjxsNE3YN8HEsw+gA4jV3aMP3w/KfOxN764C90VgVzM63pwhHgWIzOllHKA7s+Ozcb4XUufFdruwTgZugngoq8ysKLLZvHiuiic1xn0kl5hUGE1/nCd2j1imCgbKa1dXxIZWdrQ/ndQBq7tDmj7J6GeONk+1lzSw/0KSYb9Ikc7NFGcfv+GcUbnGaONH+PLT3JEOgcjBAsZ9o/U7ypb+bQLNTO/rGV+R6MsD2Kl3tgW29LD7/tPGObshbt1pufxXvrult6uqdbdKacLLrYG0WGJ/7WAY0WdY9GaB2MkM12+rl8jif51gHNbWfkp+O0ppx0HvAdWo5XrcjOvujZKOKTR1rH/6QWYhd22ANDvBX52QGtKh/URm0bf3ZAcVynEKWqIR5ddSkOf2idElSWhnTginLLp5qLnhjjUVuWDvZCTgniR01lE4nmsni0L8qDPlqhUAiILjEoZ/Skp0/jAaKynpvJHXAbnduq0r6cdC6LB8kc9Q4jH2YXCTb9dh3swQh5FTnXFCbxioAag87pFnL94fFG9BH+jWPkA5TprGDe5OCBbFTLzZBbKpUK+wl5p+poo6g7uXigw2CzbCagRDXYshWUAK8IsVGdzzygRdUN+WaYGA+yutE73QIXpRGp/JwMD7K6mfe2c7Z1pVWqPIAcrwg51LugoxHq9AQwsEo8NohqNzPn0y1KswFGXwAepIgyXxWqAgG8NRBeEeZm5nS6ZS5WGUr1I/hbB9Tp2hzcDCBpRowi3X1G7K0DQuFMNqocQtzzr68HqG8dgKhQ382oAwHOOq7fh1soqK11VRFFM5tRTznkuPGTAxTvI2rnchFuRjnlsFb/pvIq2b5EfiofkM2gFuIKOLzPio5FRPt73c/YvXXVGSW4m1EcjMAnttfVT1N76x+qyA+tgxb2akAVHNoXX1d/T3+FQ7Q72/yK/N4IwAayyh8o8hONusCb6tfsd6ik9ta/YjU4W/FJUQfVWDG/qX6Q/bGQ5odr9PEP9cI+175WFCOjURmvvv+5NCUTf03jz89YGwUsmlrH2Q+e0MqSLEvXiJ3X1W+vpuFy/hbK69/xNqrMpgjhYSX8GEpx81hesMRnPm+qv7/Og8v9SzYDYqN4N6NcNBUKrY2NjVZBfi5CY+lRvZ6acjI8Iq++adjoTDvPIZxGIHj/Zy6CDE/TRmf7XgWNJdV19Y+PAgA5HrXRoo6b0VWhViD4qvqyN+mfONOxUb0DLhpw1eKHpqzzajxio580bBR9wAV/RkEUCJB41EbfL9jN4KPcm+onQSBA4xH5+McCbTT7YWWAkMxKHAh08MiK6atGugax0fAvJ2DgYFaJwiP56GLStcNFWSUSr8RCIV5+aztCaf+GfBjCKvF4xM280pBtoWCfJI/gs+M9P/kH4NWXf0wJ8XYfjB9Qansh3qpZ/gHFWnvBe77ygvec5QXvOcsL3nOWF7znLC94z1le8J6zKPDMWloscn2t1ki9b9RqJvu3Nnlh5nezHF9kGA3TihqvJa8lD+QvNZL+HBGJ+mNYR0emYWYvZpLuFhDP3G3WE2nuWdao2Vw34vcb5MUr01iqZ6V5Z+5lbiQPN5b5z8tL+7sW7wp5WPKaydqPH7W0v1oOO1yrk+6FP+4uN0ulZn2dvdfItLmfx6fAW80ULfYsc5f8dxdfapDG9hvG8mR1g+Blfl83eSfj3w0+eOlrRvS1zKOujAm8RvLueoO3nsi7eeGVjiLrCvHqpQlR4ZWWalN4pVFjAq+0ZMR4tEXjXeq9XXNOeMvroVwdhT2qR+bJ8cxV9vY+fYdfuWZRvGZ04/qdxTt5sHZwt1oPe8cf9m7t4GC0usxHj+ON1tbu+CusUxGedcDavlq/Ii/Ua6H24jZGVg4AAG+9ZoYSD/h+LY1XZm8a9ElLD+xni+HVH6IbrbCTR5Zlmg9LdMyM8GH7hkVerFHFXDU43poZvdKspfAaV3Q0ag2zYYyWD6wQj/wet6GFd5XSemRPu400Hn/SQWxO5BeGV0s9iuPF7zWjseK3W0f8eo5He2qVaTtp7bH3OAVxoGHrJXk808TjXdDD490i/U/hlU360EYKL7khg/eQeuRi8OrrdPTL0fhp4lnlaTwzjfcQeZQM3qiWGOF88NYfGkwivCafPDU13r/5jVlllE164Tsja5xrfKYleOba5Nwz6bCW1i0j7bdLJAGgIqCEeM79d1T2zQivYdHnXtVUeM19fudarIMy8QO1A3r3gZV2LRaLLQSZ4e3Rq/aakeHEgcHkseXdqJHM/FLYhiCnRMS9GM9kI1samQq8SO5iPOrAl5gOjHJKe9bBcngdw7siV7EQt9yI9c68zVEYO5vrjdi1hPLOyOm+Jl65wV7fs7B4oTR3c7IWoseJsL5vJGbNfrKM0RJ/q35kZfGWtPGWVrlYCV6ZRaV6QzH3dvmNe3Enw5F+4G1l8fYnkrK6FT4rwaOAZZ4WxGE97FxuUEeF9ahHFI+ks7Sf/5LjPSQ38k7ujpjaR9N4S2vsToa3OlqlHX9Xm8ajd9VG9AYyeRmeIQnqWoGB4XHr263jAgPpG3N/PGkNkzKSgt2VQ3fIXYtpHKRGYQKPvEDTl3VzQXGvyfU4iowKF/fY/yyqpD1n7OvDwGBQglJ5cu6FnRjxZheJx8cQj8caLK02ypm4F0kc91ikYOuKJKUuhytA5tjmpr3JlDrEK9eWVXjTKTXtHDPPPUuOx0dhNx33SNhbJ4t402Ah8S479/RT6shzrq4eZfCso6YCbze68cBKZS1sWOqGHK9sxKMQ4jXogqt5tbrKV32NrOcU+E6N5WyEx7MrQNxLlrPJioEuxaV43DzpuinEMzPrYep2FrNaj/H4CKPxwqTgzpLjcfMkE7/GFhgk5O0nD1xlQXJmvN1MtYaVkurLiRU01uv1q8hWD5r1etzGXqa2FJaSmmHBy1glWeKVaY7qye3hO7SUxPHK5h25aumIWCX5j725ts+Blg9YM5lSUl2jlDRRCOQvGNn34/usTDUutxAY32YYtJhn1VK3hwPGy4j8geQqVhEj//MXGrWD3d3RUXTFrIXA/z+xoiwIePkzw0PKC95zlhe85ywveM9ZXvCes7zgPWd5wXvO8k/B+8EP+teXfkiJPqbxA8sL3nOW/wIGPEzYOjsspAAAAABJRU5ErkJggg==
      mediatype: image/png
  links:
    - name: Documentation
      url: 'https://github.com/RedisLabs/redis-enterprise-k8s-docs'
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    spec:
      deployments:
        - name: redis-enterprise-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: redis-enterprise-operator
            template:
              metadata:
                labels:
                  name: redis-enterprise-operator
              spec:
                serviceAccount: redis-enterprise-operator
                containers:
                  - name: redis-enterprise-operator
                    image: 'redislabs/operator-internal:559_a181cb1' 
                    command:
                    - redis-enterprise-operator
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                    imagePullPolicy: Always
                    resources:
                      limits:
                        cpu: 500m
                        memory: 100Mi
                      requests:
                        cpu: 400m
                        memory: 50Mi
                nodeSelector:
                  beta.kubernetes.io/os: linux
                serviceAccountName: redis-enterprise-operator
      permissions:
        - rules:
          - apiGroups: ["", "extensions", "apps", "rbac.authorization.k8s.io", "policy"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups:
              - app.redislabs.com
            resources:
              - '*'
            verbs:
              - '*' 
          serviceAccountName: redis-enterprise-operator
    strategy: deployment
  maintainers:  
    - email: support@redis.com
      name: 'Redis Labs, Inc'
  description: |-
      Redis Enterprise Software is enterprise grade, distributed, in-memory NoSQL database server, fully compatible with open source Redis by Redis Labs. Redis Enterprise Software extends open source Redis and delivers stable high performance, zero-downtime linear scaling and high availability, with significant operational savings.
      
      ###Core capabilities###
      * Performance at Scale
      * Active-Active Geo Distribution
      * Failsafe High Availability
      * Built-in Persistence
      * Multi-Model
      * Built-in Search
      * Intelligent Tiered Access to Memory (RAM & Flash)
      * ACID Compliant
      * Security
      * Automation and Support
      * Flexible Deployment Options (Cloud, On-Prem, Hybrid)
      * Graph-Powered Insights on Connected Data
      
      ###Operator features###
      * Basic Installation
      
      ####Prerequisites####
      A minimum of 3 nodes which support the following requirements
      * Nodes Per Cluster -  1 node minimum with at least 2 nodes for advanced cluster features
      * RAM - At least 2GB with 4GB recommended 
      * Storage - At least 10GB of free space with 20GB recommended  
      * A kubernetes version of 1.8 or higher
      * For service broker - a k8s distribution that supports service catalog (see also: service-catalog)
