apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dynamodbs.service-operator.aws
spec:
  group: service-operator.aws
  names:
    kind: DynamoDB
    listKind: DynamoDBList
    plural: dynamodbs
    shortNames:
    - ddb
    - ddbs
    - dynamo
    - dynamotable
    - dynamotables
    singular: dynamodbs
  scope: Namespaced
  version: v1alpha1
