apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticaches.service-operator.aws
spec:
  group: service-operator.aws
  names:
    kind: ElastiCache
    listKind: ElastiCacheList
    plural: elasticaches
    shortNames:
    - ec
    singular: elasticaches
  scope: Namespaced
  version: v1alpha1
