apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations: null
  name: endpoints.submariner.io
spec:
  group: submariner.io
  names:
    kind: Endpoint
    plural: endpoints
  scope: Namespaced
  version: v1
