apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hivetables.metering.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.tableName
    name: Table Name
    type: string
  group: metering.openshift.io
  names:
    kind: HiveTable
    plural: hivetables
    singular: hivetable
  scope: Namespaced
  version: v1alpha1
