apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prestotables.metering.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.tableName
    name: Table Name
    type: string
  group: metering.openshift.io
  names:
    kind: PrestoTable
    plural: prestotables
    singular: prestotable
  scope: Namespaced
  version: v1alpha1
