apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportqueries.metering.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: metering.openshift.io
  names:
    kind: ReportQuery
    plural: reportqueries
    shortNames:
    - rq
    singular: reportquery
  scope: Namespaced
  version: v1alpha1
