apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reports.metering.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.query
    name: Query
    type: string
  - JSONPath: .spec.schedule.period
    name: Schedule
    type: string
  - JSONPath: .status.conditions[?(@.type=="Running")].reason
    name: Running
    type: string
  - JSONPath: .status.conditions[?(@.type=="Failure")].reason
    name: Failed
    type: string
  - JSONPath: .status.lastReportTime
    name: Last Report Time
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: metering.openshift.io
  names:
    kind: Report
    plural: reports
  scope: Namespaced
  version: v1alpha1
