apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportdatasources.metering.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.prometheusMetricsImportStatus.earliestImportedMetricTime
    name: Earliest Metric
    type: string
  - JSONPath: .status.prometheusMetricsImportStatus.newestImportedMetricTime
    name: Newest Metric
    type: string
  - JSONPath: .status.prometheusMetricsImportStatus.importDataStartTime
    name: Import Start
    type: string
  - JSONPath: .status.prometheusMetricsImportStatus.importDataEndTime
    name: Import End
    type: string
  - JSONPath: .status.prometheusMetricsImportStatus.lastImportTime
    name: Last Import Time
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: metering.openshift.io
  names:
    kind: ReportDataSource
    plural: reportdatasources
    shortNames:
    - datasource
    - datasources
    singular: reportdatasource
  scope: Namespaced
  version: v1alpha1
