apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagelocations.metering.openshift.io
spec:
  group: metering.openshift.io
  names:
    kind: StorageLocation
    plural: storagelocations
  scope: Namespaced
  version: v1alpha1
