dist: xenial
language: python
os: linux
sudo: required

if: branch = master

python:
- "3.6"

env:
- DISTRO_TYPE=upstream KUBE_VER=v1.17.0 OLM_VER=0.14.1 SDK_VER=v0.16.0

before_install:
# check-pr needs to be sourced so it can pass the test early.
- source scripts/ci/check-pr $DISTRO_TYPE

install:
- scripts/ci/install-deps $DISTRO_TYPE

jobs:
  include:
  - stage: catalog build
    name: Test loading the Operator into the Community Catalog
    install: skip
    script:
    - docker build --build-arg PERMISSIVE_LOAD=false -f upstream.Dockerfile -t operatorhub-catalog:dev . 
  - stage: operator test
    name: Test the Operator using operator-sdk running on minikube
    script: scripts/ci/run-tests.sh

