apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtcontrollers.virt.konveyor.io
spec:
  group: virt.konveyor.io
  names:
    kind: VirtController
    listKind: VirtControllerList
    plural: virtcontrollers
    singular: virtcontroller
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
