apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: electedleaders.agent.instana.io
  namespace: local
spec:
  group: agent.instana.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: ElectedLeader
    listKind: ElectedLeaderList
    plural: electedleaders
    singular: electedleader
    shortNames:
    - el
