apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: agents.instana.io
  namespace: instana-agent
spec:
  group: instana.io
  names:
    kind: InstanaAgent
    plural: agents
    shortNames:
    - ia
    singular: agent
  scope: Namespaced
  version: v1beta1
