apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: miganalytics.migration.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=='Ready')].status
    name: Ready
    type: string
  - JSONPath: .spec.migPlanRef.name
    name: Plan
    type: string
  - JSONPath: .status.analytics.percentComplete
    name: Progress
    type: string
  - JSONPath: .status.analytics.k8sResourceTotal
    name: Resources
    type: string
  - JSONPath: .status.analytics.imageCount
    name: Images
    type: string
  - JSONPath: .status.analytics.imageSizeTotal
    name: ImageSize
    type: string
  - JSONPath: .status.analytics.pvCount
    name: PVs
    type: string
  - JSONPath: .status.analytics.pvCapacity
    name: PVCapacity
    type: string
  group: migration.openshift.io
  names:
    kind: MigAnalytic
    plural: miganalytics
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            analyzeImageCount:
              type: boolean
            analyzeK8SResources:
              type: boolean
            analyzePVCapacity:
              type: boolean
            listImages:
              type: boolean
            listImagesLimit:
              format: int64
              type: integer
            migPlanRef:
              type: object
          required:
          - migPlanRef
          - analyzePVCapacity
          - analyzeImageCount
          - analyzeK8SResources
          type: object
        status:
          properties:
            analytics:
              properties:
                excludedk8sResourceTotal:
                  format: int64
                  type: integer
                imageCount:
                  format: int64
                  type: integer
                imageSizeTotal:
                  type: string
                incompatiblek8sResourceTotal:
                  format: int64
                  type: integer
                k8sResourceTotal:
                  format: int64
                  type: integer
                namespaces:
                  items:
                    properties:
                      excludedK8SResourceTotal:
                        format: int64
                        type: integer
                      excludedK8SResources:
                        items:
                          properties:
                            count:
                              format: int64
                              type: integer
                            group:
                              type: string
                            kind:
                              type: string
                            version:
                              type: string
                          required:
                          - group
                          - version
                          - kind
                          - count
                          type: object
                        type: array
                      imageCount:
                        format: int64
                        type: integer
                      imageSizeTotal:
                        type: string
                      images:
                        items:
                          properties:
                            name:
                              type: string
                            reference:
                              type: string
                            size:
                              type: string
                          required:
                          - name
                          - reference
                          - size
                          type: object
                        type: array
                      incompatibleK8SResourceTotal:
                        format: int64
                        type: integer
                      incompatibleK8SResources:
                        items:
                          properties:
                            count:
                              format: int64
                              type: integer
                            group:
                              type: string
                            kind:
                              type: string
                            version:
                              type: string
                          required:
                          - group
                          - version
                          - kind
                          - count
                          type: object
                        type: array
                      k8sResourceTotal:
                        format: int64
                        type: integer
                      k8sResources:
                        items:
                          properties:
                            count:
                              format: int64
                              type: integer
                            group:
                              type: string
                            kind:
                              type: string
                            version:
                              type: string
                          required:
                          - group
                          - version
                          - kind
                          - count
                          type: object
                        type: array
                      namespace:
                        type: string
                      pvCapacity:
                        type: string
                      pvCount:
                        format: int64
                        type: integer
                    required:
                    - namespace
                    - k8sResourceTotal
                    - excludedK8SResourceTotal
                    - incompatibleK8SResourceTotal
                    - pvCapacity
                    - pvCount
                    - imageCount
                    - imageSizeTotal
                    type: object
                  type: array
                percentComplete:
                  format: int64
                  type: integer
                plan:
                  type: string
                pvCapacity:
                  type: string
                pvCount:
                  format: int64
                  type: integer
              required:
              - plan
              - percentComplete
              - k8sResourceTotal
              - excludedk8sResourceTotal
              - incompatiblek8sResourceTotal
              - pvCapacity
              - pvCount
              - imageCount
              - imageSizeTotal
              type: object
            observedGeneration:
              format: int64
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
