apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: skydive-operator.v0.0.1
  namespace: placeholder
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.helm.k8s.io/v1alpha1",
          "kind": "NetflowCollector",
          "metadata": {
            "name": "netflow-collector"
          },
          "spec": {
            "exporter": {
              "enabled": true,
              "store": {
                "bucket": "default",
                "objectPrefix": "default"
              },
              "write": {
                "s3": {
                  "use_api_key": false,
                  "access_key": "admin",
                  "secret_key": "admin1234",
                  "api_key": "",
                  "installLocalMinio": true,
                  "endpoint": "http://localhost:9000",
                  "region": "default"
                }
              }
            },
            "image": {
              "repository": "cognetive/skydive",
              "tag": "2019.10.15___12.24"
            }
          }
        },
        {
          "apiVersion": "charts.helm.k8s.io/v1alpha1",
          "kind": "Skydive",
          "metadata": {
            "name": "skydive"
          },
          "spec": {
            "agent": {
              "topology": {
                "probes": "ovsdb docker runc"
              }
            },
            "analyzer": {
              "topology": {
                "fabric": "TOR1-\u003e*[Type=host]/eth0"
              }
            },
            "arch": {
              "amd64": "2 - No preference",
              "ppc64le": "2 - No preference",
              "s390x": "2 - No preference"
            },
            "dataVolume": {
              "existingClaimName": "",
              "name": "datavolume",
              "size": "10Gi",
              "storageClassName": ""
            },
            "elasticsearch": {
              "image": {
                "repository": "elastic/elasticsearch",
                "tag": "5.5.1"
              }
            },
            "env": [],
            "etcd": {
              "port": 12379
            },
            "exporter": {
              "enabled": false,
              "env": [
                {
                  "name": "SKYDIVE_LOGGING_LEVEL",
                  "value": "INFO"
                },
                {
                  "name": "SKYDIVE_FLOW_UPDATE",
                  "value": "30"
                },
                {
                  "name": "SKYDIVE_ANALYZER_STARTUP_CAPTURE_GREMLIN",
                  "value": "G.V().has('Name', NE('lo'))"
                },
                {
                  "name": "SKYDIVE_ANALYZER_STARTUP_CAPTURE_BPF",
                  "value": "not (tcp dst port 8082)"
                },
                {
                  "name": "SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE",
                  "value": "L3"
                },
                {
                  "name": "SKYDIVE_ANALYZER_STARTUP_CAPTURE_TYPE",
                  "value": "pcap"
                },
                {
                  "name": "SKYDIVE_AGENT_CAPTURE_SYN",
                  "value": "True"
                }
              ],
              "env_exporter": [
                {
                  "name": "SKYDIVE_PIPELINE_STORE_BUFFERED_MAX_FLOWS_PER_OBJECT",
                  "value": "60000"
                },
                {
                  "name": "SKYDIVE_PIPELINE_STORE_BUFFERED_MAX_SECONDS_PER_OBJECT",
                  "value": "60"
                },
                {
                  "name": "SKYDIVE_PIPELINE_STORE_BUFFERED_MAX_FLOW_ARRAY_SIZE",
                  "value": "100000"
                },
                {
                  "name": "SKYDIVE_PIPELINE_STORE_BUFFERED_MAX_SECONDS_PER_STREAM",
                  "value": "86400"
                }
              ],
              "image": {
                "repository": "docker.io/bluesecure/skydive-exporter",
                "tag": 1
              },
              "store": {
                "bucket": "default",
                "buffered": {
                  "max_flows_per_object": 60000
                },
                "objectPrefix": "default"
              },
              "write": {
                "s3": {
                  "use_api_key": true,
                  "access_key": "admin",
                  "secret_key": "admin1234",
                  "api_key": "",
                  "installLocalMinio": true,
                  "endpoint": "http://localhost:9000",
                  "region": "default"
                }
              }
            },
            "image": {
              "imagePullPolicy": "IfNotPresent",
              "repository": "skydive/skydive",
              "secretName": "",
              "tag": "0.24.0"
            },
            "nameOverride": "skydive",
            "persistence": {
              "enabled": false,
              "useDynamicProvisioning": false
            },
            "resources": {
              "limits": {
                "cpu": "2000m",
                "memory": "8192Mi"
              },
              "requests": {
                "cpu": "100m",
                "memory": "512Mi"
              }
            },
            "service": {
              "name": "skydive",
              "port": 8082,
              "type": "NodePort"
            },
            "storage": {
              "elasticsearch": {
                "host": "127.0.0.1",
                "port": 9200
              },
              "flows": {
                "indexEntriesLimit": 10000,
                "indicesToKeep": 10
              },
              "topology": {
                "indexEntriesLimit": 10000,
                "indicesToKeep": 10
              }
            }
          }
        }
      ]
    categories: 'Security, Networking, Monitoring'
    certified: 'false'
    createdAt: 'Jan 14, 2020 11:40 am'
    description: >-
      Skydive is an open source real-time network topology and protocols
      analyzer, that can be used also as a netflow collector.
    containerImage: ''
    support: ''
    capabilities: Basic Install
    repository: ''
spec:
  displayName: skydive-operator
  description: |
    Skydive is an open source real-time network topology and protocols analyzer. It aims to provide a comprehensive way of understanding what is happening in the network infrastructure. It can be used as netflow collector.
  maturity: alpha
  version: 0.0.1
  replaces: ''
  minKubeVersion: ''
  keywords: []
  maintainers:
    - name: ''
      email: ''
  provider:
    name: IBM
  labels: {}
  selector:
    matchLabels: {}
  links:
    - name: skyDive
      url: 'https://github.com/skydive-project/skydive'
  icon:
    - base64data: 'iVBORw0KGgoAAAANSUhEUgAAAJgAAAAqCAYAAABPwJJfAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH4QIbDCMf1q9iiQAAEuRJREFUeNrtm3mcFdWVx7+n6m29L2yijaD0AjSgsphFUWMkMSIQFYiZ5KNG4yQx42RIYpbJiJpxGScxMZqMJCYfkowQw2KEKEISUJRV0URRlqbBFgW66aa318vr96rqzB99n1ba9153K5+EzvT9fOpVvXvPPffWPb97tqqCwTJYBstgGahF/tYDFpeW0lhd/Vd1BeXlheJ5Q1AvD8gGgqABEBdwgBgi7ZZltyo0NlVVdfr7hyoqiO/bNyjNQYC9U4rKy69A9VpVbwaqWVYwbNmhiCWhiGVZtiAWeC6qrnquo16iy3O7Yh6qHkKHIFuwZD3IqqZ9+44NivL/GcAiY8YQq6npBlNZ2WT13AsUPT8Qzjknu2hEed7QUeQOH0Pu0NOIFAwjFMnFScSId7Sj6qGuh3qK53oIFnYwQryrjc5oPR2tDXS21ON0tpLoaCLR3lSf6GjeCPxBsda3VFcfBqCyEl57bVDK/4gAK582jWOtrR8TeNgKBE/PGjaKSNEphLLyCGXlE87KIZJTSDi7kHBOIeHsPESslLzam+uorX6B6PFaAoEQguB5LomuLsQOI7aNE2+l8/hbxJuPoeptULg+CIfqq6oYMm4cx/fuHZT2QAZYcUUFjcYPKiwr/azrut8YNf7cSZXTZzJy9Hiyc/K6NZLn4LrJw8VzHTxzbQdDxB2X3S89zeu7d+LGWhk1vIjh+TkU5eXT2dmJeh6qCqq4notlWXieRzzh0NwaJeYkiMUT1DY0ICKPB2z7q01VVa8PivofQIMVl5fnKzwRyi2ccfH8hYweOxHPdfrUVz2P6r072fb7xYwoLOAL11xDYSTCizt34nke+QUFFBUVkZubSzgcJhKJvOscDASItrXR0tzs1NTUdD66Zk10/5Ej99fv2fO9QVEPQIAVVVTQlNRa5WX/gth3TpzxyYIPXbyAcCQb9dxu8ACovgMm8ysIlh3gjYOvse43P2TG5FI+OGkyrY2NHG9oICs7m/z8fEKhEOFwmHA4TFZWFpFIBNu2aWtrIxaLkUgkXnYcZy/wciAQ2FNbW3tk8+bNb23evDkENA+vrGyu3717UNoDBWBF5eU0VVVRNG5cUF3ncrECSyMFQ7IKR08kr2AIjuMghrNtBwgEggQCQWw7gGXbBOwAiOB5HscOH+Dork185+abCSYSW1c+9tgto0aNeqOjoyM/EAhMKygouHbYsGHTc3JyAqraHI1GG5uamrYcPnz42fr6+k3btm07nFYrqt4lIt8ZFPMA1GBF5RXD1HOeDhaPrDzvo/O48mMzcTzFcT0SjpLwPBxHSbgecdfDcbuvFQFVbNtm1ZK7Kcm3WbRwIeuefPKOe+655/ZUY82dO/eUgoKCrIaGhqa1a9c2+9tuuOEGWltbWbFiRU9wXQa8ICL1g2IeIABLmsTCsrLpYtk7Rk08T+Z/6kbKTi9h95vH8fQdhkkNJqYm+T8UDBBrb2LFz+/kurmXMmfmTHfRbbctWrFixd3z5s1j5cqVqTTR2SLylz75ct2mWICrRGSlqiIig5IeKBqsaNy4D6NsmXrpNVx+6ZV0dDnEHa9PfYO2EG09zsP33syyB+9n5LBh3r333jt76dKla3sBzWwR+X1f56iqEWC6iDw3KOK/b7H6BKqxY7vPZaVj1NMN51xytV540VzaOhN9BpdtCaAs/dmd3PXNr1M6Zgy33nrrvy1dunTt/Pnze8VMP+/r3wfBNYAA1nTggKG2t48+5yORi2cuENd1cby+yz0rHGTVqp9TWVLMvFmz2Lhx45rVq1c/CLzLf0ph8vqquVDVycDjg6I9OUogU2NhWRnN+/dTXFEe8hxnddawUSM+NGM2sVjsbb/G81wcJ0EiEScejxGPd9EVjxGPx0jE4yQSXTiOQ2esk5qXn+Prt3UHdVu3bv31ggULWL58eWYbLtJnkBnaM0Xk8UHf6yQHWHF5OY1VVRSUlhYrcjDv9PEFWcWnsmHjY+9y42zbIhCKEI7kEgplEQxnEY7kEApnE8rNJy+cQ/T1V8gP21xx2WVs37HDXbt27da6urq+ztPrz00NgmsAAKyxqori8rIhWPau3JJxBaMqZ3BO5WRGFOeTnx0h7gkxBxKeTdwDx/WIOx5djvt2UlVRgrZFtLWR155dye8eepC3Dh9m+fLli+rq6o72BzN9BNaXgV8PivUkB1hRRQV4XkDFqi48Y3LhB2Zew8VTJ1A6NIcdrx9n19Fod0pCutMQmZRFKBxk/4t/YMbk8UwoL2f9+vVbHnroobuvuuoqVq1adUIAZkxoAdAmItFBsZ7ETn5xaSlN+/bhee5DOSPPLLxozhf46NQJ7D/ayiPbajhQ14aIYFuCJZnBpUDQtnjj1S1cd/WnsW2bnTt3rgT6A65eTaQxh+cAS/sTFAyWv4MGa6yupqis7FQ7K/fzH/zEjZxbMZrn9h0jHLBMqqEfqPCUwiyL9miUirIyVJWnnnrqvbygpX3wt0YBzqDvNRDSFCKrT5twHhPKK9hfGyUcsN4bc0soKQwDEI12Wy7Xdb0TCTATOV4BbBoE10AwkeXlpyIyrWTcdOqaO2jtTLxn5h+fNJJIUAhm5XCgpgYRYcqUKSPnzJnTf4SlMX2qGgDOEJFDg+ZxAADMc53KUG6R5uQV46nSm1IQEUQsxLKwLBvbDhAMBjmtOJdXDrzJ45u2E8kr5JXd3ZZx+vTpU9esWdPviabSTgZQ5cCSdDSD5eSLIvOtUFi6gWPAI4KnHvFYR/cR7yDR1UkiHqMr1t5d19VBwknguA6O4xB3HOxQhEAgDJZNRyyGqpKfn59/Iiae9L1UdTrwyKAoBwrALKvW6YhqrCMq6rkcrzvE8fo36Yg2oioEsnIJRHKxw3nYkWzscB7BIacQDmUT9r9TL90/TmcrDXu3cuqIU/qV0+qLRlPVUuCoiLh9Ma/ptGDP+p5174UmU7K3P7R93Wj9cTPez9j9pQ+kcKe7UGX3q9vJGTKSiWeO4exJlTh2BE/CJDyPWMKhsb2L5vaubrxoatyoQmFuNrZldX8ppEphYeEZJ3CDzBOR/+rDTZ8OXKmqU811BIgBh4DVwMoUmvFW4ExglYg8kWKBz1bVm4Ew8EMReVFVbwNKTMDxSAbhnKWqCwEX+JaI1KvqecB1PnIX6DBz3CQif04FTHNeCEzoZa32icj3Df31wPnAIRG5vRcLMRK4w6iMbwAtqnonMKwPgVlbCoB5uRII8ZELZ3LTZefxm+cP8lxVLZbV/fyxX/tMIBSOkJ1fzKHDh5MAm3qCTGQJ8NtUmsm3OCHgfuBLdH/A2w68CRQDw4ELgM+q6sUi8rRPM54PfNf8/5yfp2n/MvBjoAm4UER2maGnA7OAHFV9pOe8TN8PAc8CLcAU3wuRDwBTgITPBthJW6Cqt4vIHSn4DQX+2whUgZBpdny7XoBrfAD9OjAe+FUv4BoGvGV89ctFpElVpwHf9G2CdCUI3Jgq/xAQsSg9pYjvr9/Fs1W1BGyrO6naXzMGiB2kcNQ49lZV4XoeJSUlBbNmzbqkH0CKAPEU0eQHgdpUkaNZnGLgRQOuW4DRIlIoIpNE5DTgbF+XkUneBpSLTf3cHgs+SVV3GnB9FygRkV2+Oew350IfMFDV5PVdwFZgHTBeRA6Z+q8YcFUbDTgWmGTGT34RdbuqTkyxRF3AGcAYYKavfrKpTx6P+gA/3pz/lMH9yAGeN+D6pIg8aZp/a+q+asY8I81xuoj8PJCCe9Rzumhs7+JgQ4ygbb0vTWMLjCybygsvPElnZyclJSWMHTv2m+luLkUZajSP/+YjwDAR6UzjZwiwHKgErhWRX/cEooi8pqpRoAZ4yQeimabfq8B6Qx5S1S8ZbVgDjBWRgyl8GvNeEwWApaqu4Wmr6koDmCUicr0BHsAI4Pum30Ui4v9Kfa+qHgF2mv8VZl7++4ia+xBgmam+RUT2pPEdz/T9/VMazVVgNH2ecUNWm/ZvG7dht4j8qC/+2LvQI5Zd43S2y4tVbzA0J/y+PfL6aIyZU8bjDRnL/Q8/TDgU4qyzzrqgHyyGAm096v5ZRB7KkM44H/ioMUPL0yy0BQwRkckistcsbBj4nSH5vIh0qep4I+CkqR2XBFeKxT3o12CG5whgrwHXbBG5vsdcbzG+8C9F5HAKjdzhu/5zBr9uMnAhcAxYnEH4SS2YEJHaNKmgHQZc80VklaqKquYarRUH5r3nPFhTVVUd6J8OvLSBpo4Y8j6+bFPA8TzGjcijYtol/GzpMuoaGsjPzxdjo/ulwVS12IDgz5mSr8AXzTkCfBjISQFET0QSPfg8aOa1RER2qOpXgd1mncpEZLExSSn9PuOTuQZgrqpeAtQav+h0EXnCr/VU9TTga4bFrWlA8SlzrvZrzRSgWGfO/y4ibRk0SxJg21IEC7mqWmM05Wd83zQosMjI4ikR2dNLbjJjHgxgTlPV81VWIFQycvoVSCD4V981plAb3UA0AwZtm0goQMgWIpJg1bZXCEfCFJ56Bj9avJi2+vrf+JzZ3soQoM1M/D6gHrhHVe0M6YklwD8ZgK0HjqnqLmCxiDzeM9w2wi4ErjVab4WqvmEizjXAlcmx0gnO8Gg1znWO8dNuMlHqp0Wk0z+m8cuSJvhGEXkrhaCygM+Yqs9l8FO/A5wCPCMiv+glTVHRE2C+e9oMjDbgWuYzmecYTQuQUNWf8u7vOQR4Q0Tu7Fn5rlI8fjzquqXqeevzR084c1jlxdiRXMQOYAVC3d80JrrwEl248Q7crg6cWBtuV8fb/xOdURIdrbjxGG68s83raq9H9QgqG5oPVN/W19yKidh+SvcbFeuMI7sbmJbOBzOLMsNEOxOM05ksMWA+8ESPkP8ZY2JagHxjCsJGEBeISK+fqJvIdg+Qa6oWich/9gCW39dbZwKD8YCmoFlgnOpXgHOBrhSaM8v4hUNMoPBKhrUU4Glzn1eJyGMGdGFgCzAVuE5EftXDn33GRNxxE9mmdLeBChGp6hVgyVJUXp6DyEYR69y/1lRmcPVAaUQ4qqpHgXpU64BaVA8B1Z56BwWJi0hCAoFE4549rpn4bCP8n4hIW4aE5m0icod55rjdaIepItLRm5NpxokYf+IW3y58CygVkS5DNw9IfhjQbtINtwMLgDrj1Lf3IYk5wgAmD5icjDDTmJIGA4pPicjyFO3DzdgY81ydZtwlJn/2lIhc1stmtc38SozrsNMAeYv5/3kR+UUPM/4Bs+4NJviJpVsCE3D0P2msqtbho0cvfOEvf5m9dsOGBU/88Y9X19XXT1fVvL70zysvz8R7lqrOV9VLVPXcFO2lvuv/MYuU1u5neuCtqou0u1Srasjne7yqqp6qPuCjnafvlJK+ZMhV9duG/tFMc1HVew3dph79/dcvGJovpuJlaKcZmg6TXsk4RxPNeqrapqqnGed9veFxQ4q1DKhqs2mffcKfIxUYYCRzOT2Okap6kap+QVVv9x3fVtWrVLXSaJ2MQvEvrKoOV9U7VPUmsxiiqnM9z/tJNBqds2zZMjud4FQ1R1WH9AKAR81i/dBvgk3dwR59KlQ1Ztq+0odNWOQD5IgMQh6hqk2q2mmy5KnAs8nwWZkOXOa8ztDd1NvmMu1lhv64+b/K/L85BcAx8lRVXX1SPeA00d54Vb1AVS/2HZeo6qWqermqzvEdn1DVs1T1dFW9UFWzDZ9vJCXmuq5u2bLlgRRjnaaqhw1ZaQqBJq9vMjSvqqpl2k41O1pVdXSPvvmqWmvaXswA7OTme9bQfrkXUPzS0P0qxUarUNWtpv0Hvazxx5JgUdVIX15VMspAVXWZqj5grm9MM9+wqraY9Zk4oF+FUtWgyZJfr6pHVPVFVS1Q1Zd9WkH37NnT7guzk30n+jTN3UlfwxxBVc1W1Z/4TGOWT9g/NvU/SrPIO3zDSwbNOEVVXVXd7+efgv7DPn4RQ5ulqmeq6v8m95KqXttDs0sP+jxVjRv6mcbcZ6lqsJd1Xm76rDDnb6VzMVR1taF53MwhK8NxUoOrZ/Lz7eI4zjN+gG3atKnFpB/8fbJV9aiP7KCqbjbHXl/915Ka0fQb6zdpabTTv/poLspwD4cMzdUZTGNAVV8ydAlVbTT+jeur+66qnprCLxurqnXGtDYZHypZGgyfRlX9eC9r3eTrl8m3u8BH1+IbN9XxXE+59SUP9jcr/ohDRDx/NNnQ0HBXbm7uOYFAIK+lpSV+3333PQ+83KN/BzBSVb8HfNJEjaNNPupl4DYR+W2KxfwP81xwiYik+0BzmclDdZg8UyqhzTGPVZ4TkUdTRVEmGisxfJ72NbUD+4Ankw/bez5+Mn2vNOmPTK+btwAbM0Sttkl3CLBORBZnmOvMHvPMlKj/QVJu6Z5Hn5SlpaWFgoICFi5ceNbRo0fn1tTUHNm+ffsa8ygkbQ4tGWX2TMKmykVlysO913fA0mX5/xbve50Ivu9lvEx9/g9shMpW7+f5jwAAAABJRU5ErkJggg==
'
      mediatype: 'image/png'
  customresourcedefinitions:
    owned:
      - name: netflowcollectors.charts.helm.k8s.io
        displayName: Skydive netflow collector
        kind: NetflowCollector
        version: v1alpha1
        description: Skydive netflow collector
        resources:
          - version: v1
            kind: Deployment
          - version: v1
            kind: Service
          - version: v1
            kind: ReplicaSet
          - version: v1
            kind: Pod
          - version: v1
            kind: Secret
          - version: v1
            kind: ConfigMap
        specDescriptors: []
        statusDescriptors: []
      - name: skydives.charts.helm.k8s.io
        displayName: Skydive
        kind: Skydive
        version: v1alpha1
        description: SkyDive
        resources:
          - version: v1
            kind: Deployment
          - version: v1
            kind: Service
          - version: v1
            kind: ReplicaSet
          - version: v1
            kind: Pod
          - version: v1
            kind: Secret
          - version: v1
            kind: ConfigMap
        specDescriptors: []
        statusDescriptors: []
    required: []
  install:
    strategy: deployment
    spec:
      permissions: []
      clusterPermissions:
        - serviceAccountName: skydive-operator
          rules:
            - apiGroups:
                - ''
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - ''
              resources:
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - networking.k8s.io
              resources:
                - networkpolicies
              verbs:
                - '*'
            - apiGroups:
                - ''
              resources:
                - configmaps
                - pods
                - secrets
                - serviceaccounts
                - services
              verbs:
                - '*'
            - apiGroups:
                - extensions
              resources:
                - daemonsets
                - deployments
                - ingresses
                - podsecuritypolicies
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - statefulsets
                - deployments
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - skydive-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - replicasets
              verbs:
                - get
            - apiGroups:
                - charts.helm.k8s.io
              resources:
                - '*'
                - netflowcollectors
              verbs:
                - '*'
            - apiGroups:
                - policy
              resources:
                - podsecuritypolicies
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
                - roles.rbac.authorization.k8s.io
                - authorization.k8s.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - '*'
      deployments:
        - name: skydive-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: skydive-operator
            template:
              metadata:
                labels:
                  name: skydive-operator
              spec:
                serviceAccountName: skydive-operator
                containers:
                  - name: skydive-operator
                    image: 'quay.io/sacloud/skydive-op:v0.0.2'
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        value: ''
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: skydive-operator
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
