apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodenetworkconfigurationpolicies.nodenetwork.openshift.io
spec:
  group: nodenetwork.openshift.io
  names:
    kind: NodeNetworkConfigurationPolicy
    listKind: NodeNetworkConfigurationPolicyList
    plural: nodenetworkconfigurationpolicies
    singular: nodenetworkconfigurationpolicy
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            desiredState:
              properties:
                interfaces:
                  items:
                    properties:
                      mtu:
                        type: integer
                      name:
                        pattern: ^(.*)$
                        type: string
                      numVfs:
                        type: integer
                    required:
                    - name
                    type: object
                  type: array
              required:
              - interfaces
            priority:
              maximum: 99
              minimum: 0
              type: integer
          required:
          - priority
          - desiredState
      required:
      - spec
  version: v1alpha1
