---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federatedtypeconfigs.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederatedTypeConfig
    plural: federatedtypeconfigs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            enableStatus:
              type: boolean
            federatedType:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
            namespaced:
              type: boolean
            propagationEnabled:
              type: boolean
            status:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
            target:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
          required:
          - target
          - namespaced
          - propagationEnabled
          - federatedType
          type: object
        status:
          properties:
            observedGeneration:
              format: int64
              type: integer
            propagationController:
              type: string
            statusController:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
