apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[\n  {\n    \"apiVersion\": \"descheduler.io/v1alpha1\",\n    \"\
      kind\": \"Descheduler\",\n    \"metadata\": {\n      \"name\": \"example-descheduler-1\"\
      \n    },\n    \"spec\": {\n      \"schedule\": \"*/1 * * * ?\",\n      \"strategies\"\
      : [\n        {\n          \"name\": \"lownodeutilization\",\n          \"params\"\
      : [\n            {\n              \"name\": \"cputhreshold\",\n            \
      \  \"value\": \"10\"\n            },\n            {\n              \"name\"\
      : \"memorythreshold\",\n              \"value\": \"20\"\n            },\n  \
      \          {\n              \"name\": \"memorytargetthreshold\",\n         \
      \     \"value\": \"30\"\n            }\n          ]\n        }\n      ]\n  \
      \  }\n  }\n]"
    capabilities: Seamless Upgrades
    categories: OpenShift Optional
    certifiedLevel: Primed
    containerImage: registry.svc.ci.openshift.org/openshift/origin-v4.0:descheduler-operator
    createdAt: 2019/11/15
    description: An operator to run the OpenShift descheduler, a scheduler to move
      running Pods according to policies
    healthIndex: B
    repository: https://github.com/openshift/descheduler-operator
    support: Red Hat
  name: descheduler.v0.0.1
  namespace: openshift-descheduler-operator
spec:
  customresourcedefinitions:
    owned:
    - description: Represents an instance of a Descheduler application
      displayName: Descheduler Operator
      kind: Descheduler
      name: deschedulers.descheduler.io
      version: v1alpha1
  description: "# Descheduler for Kubernetes\n\n## Introduction\n\nScheduling in Kubernetes\
    \ is the process of binding pending pods to nodes, and is performed by\na component\
    \ of Kubernetes called kube-scheduler. The scheduler's decisions, whether or where\
    \ a\npod can or can not be scheduled, are guided by its configurable policy which\
    \ comprises of set of\nrules, called predicates and priorities. The scheduler's\
    \ decisions are influenced by its view of\na Kubernetes cluster at that point\
    \ of time when a new pod appears first time for scheduling.\nAs Kubernetes clusters\
    \ are very dynamic and their state change over time, there may be desired\nto\
    \ move already running pods to some other nodes for various reasons\n\n* Some\
    \ nodes are under or over utilized.\n* The original scheduling decision does not\
    \ hold true any more, as taints or labels are added to\nor removed from nodes,\
    \ pod/node affinity requirements are not satisfied any more.\n* Some nodes failed\
    \ and their pods moved to other nodes.\n New nodes are added to clusters.\n\n\
    Consequently, there might be several pods scheduled on less desired nodes in a\
    \ cluster.\nDescheduler, based on its policy, finds pods that can be moved and\
    \ evicts them. Please\nnote, in current implementation, descheduler does not schedule\
    \ replacement of evicted pods\nbut relies on the default scheduler for that.\n\
    \n## Note\n\nAny api could be changed any time with out any notice. That said,\
    \ your feedback is\nvery important and appreciated to make this project more stable\
    \ and useful.\n"
  displayName: Descheduler
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - services
          - pods
          - configmaps
          - secrets
          - names
          - nodes
          - pods/eviction
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - batch
          - extensions
          resources:
          - jobs
          - cronjobs
          verbs:
          - '*'
        - apiGroups:
          - descheduler.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: openshift-descheduler
      deployments:
      - name: descheduler-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: descheduler-operator
          template:
            metadata:
              labels:
                app: descheduler-operator
            spec:
              containers:
              - command:
                - descheduler-operator
                env:
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: OPERATOR_NAME
                  value: descheduler-operator
                image: registry.svc.ci.openshift.org/openshift/origin-v4.0:descheduler-operator
                imagePullPolicy: Always
                name: descheduler-operator
              restartPolicy: Always
              serviceAccount: openshift-descheduler
              serviceAccountName: openshift-descheduler
              terminationGracePeriodSeconds: 5
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - deschedule
  - scale
  - binpack
  - efficiency
  labels:
    olm-owner-enterprise-app: descheduler-operator
    olm-status-descriptors: descheduler.v0.0.1
  maintainers:
  - email: support@redhat.com
    name: Red Hat
  provider:
    name: Red Hat
  version: 0.0.1
