#! package-manifest: deploy/chart/catalog_resources/rh-operators/prometheusoperator.0.22.2.clusterserviceversion.yaml
packageName: prometheus
channels:
- name: preview
  currentCSV: prometheusoperator-community.0.22.2
