apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudformationtemplates.service-operator.aws
spec:
  group: service-operator.aws
  names:
    kind: CloudFormationTemplate
    listKind: CloudFormationTemplateList
    plural: cloudformationtemplates
    shortNames:
    - cft
    - cfts
    - cfn
    - cfns
    - cloudformation
    singular: cloudformationtemplates
  scope: Namespaced
  version: v1alpha1
