apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ecrrepositories.service-operator.aws
spec:
  group: service-operator.aws
  names:
    kind: ECRRepository
    listKind: ECRRepositoryList
    plural: ecrrepositories
    shortNames:
    - ecr
    - repository
    singular: ecrrepositories
  scope: Namespaced
  version: v1alpha1
