apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: s3buckets.service-operator.aws
spec:
  group: service-operator.aws
  names:
    kind: S3Bucket
    listKind: S3BucketList
    plural: s3buckets
    shortNames:
    - s3
    - bucket
    - buckets
    singular: s3buckets
  scope: Namespaced
  version: v1alpha1
