apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snssubscriptions.service-operator.aws
spec:
  group: service-operator.aws
  names:
    kind: SNSSubscription
    listKind: SNSSubscriptionList
    plural: snssubscriptions
    shortNames:
    - subscription
    singular: snssubscriptions
  scope: Namespaced
  version: v1alpha1
