apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snstopics.service-operator.aws
spec:
  group: service-operator.aws
  names:
    kind: SNSTopic
    listKind: SNSTopicList
    plural: snstopics
    shortNames:
    - sns
    - topic
    - topics
    singular: snstopics
  scope: Namespaced
  version: v1alpha1
