apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sqsqueues.service-operator.aws
spec:
  group: service-operator.aws
  names:
    kind: SQSQueue
    listKind: SQSQueueList
    plural: sqsqueues
    shortNames:
    - sqs
    - queue
    - queues
    singular: sqsqueues
  scope: Namespaced
  version: v1alpha1
