apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "storage.dell.com/v1",
          "kind": "CSIIsilon",
          "metadata": {
            "name": "isilon",
            "namespace": "test-isilon"
          },
          "spec": {
            "driver": {
              "common": {
                "envs": [
                  {
                    "name": "X_CSI_VERBOSE",
                    "value": "1"
                  },
                  {
                    "name": "X_CSI_ISI_ENDPOINT",
                    "value": "1.1.1.1"
                  },
                  {
                    "name": "X_CSI_ISI_PORT",
                    "value": "8080"
                  },
                  {
                    "name": "X_CSI_ISI_PATH",
                    "value": "/ifs/data/csi"
                  },
                  {
                    "name": "X_CSI_ISILON_NO_PROBE_ON_START",
                    "value": "false"
                  },
                  {
                    "name": "X_CSI_ISI_AUTOPROBE",
                    "value": "true"
                  },
                  {
                    "name": "X_CSI_ISI_INSECURE",
                    "value": "true"
                  },
                  {
                    "name": "X_CSI_DEBUG",
                    "value": "false"
                  }
                ],
                "image": "dellemc/csi-isilon:v1.1.0",
                "imagePullPolicy": "IfNotPresent"
              },
              "configVersion": "v1",
              "controller": {
                "envs": [
                  {
                    "name": "X_CSI_ISI_QUOTA_ENABLED",
                    "value": "true"
                  },
                  {
                    "name": "X_CSI_ISI_ACCESS_ZONE",
                    "value": "System"
                  }
                ]
              },
              "forceUpdate": false,
              "node": {
                "envs": [
                  {
                    "name": "X_CSI_ISILON_NFS_V3",
                    "value": "false"
                  }
                ]
              },
              "replicas": 1,
              "sideCars": [
                {
                  "name": "snapshotter"
                }
              ],
              "snapshotClass": [
                {
                  "name": "volumesnapshotclass",
                  "parameters": {
                    "IsiPath": "/ifs/data/csi"
                  }
                }
              ],
              "storageClass": [
                {
                  "default": true,
                  "name": "storageclass",
                  "parameters": {
                    "AccessZone": "System",
                    "AzServiceIP": "1.1.1.1",
                    "IsiPath": "/ifs/data/csi",
                    "RootClientEnabled": "false"
                  },
                  "reclaimPolicy": "Delete"
                }
              ]
            }
          }
        },
        {
          "apiVersion": "storage.dell.com/v1",
          "kind": "CSIPowerMax",
          "metadata": {
            "name": "test-powermax",
            "namespace": "test-powermax"
          },
          "spec": {
            "driver": {
              "common": {
                "envs": [
                  {
                    "name": "X_CSI_POWERMAX_ENDPOINT",
                    "value": "https://0.0.0.0:8443/"
                  },
                  {
                    "name": "X_CSI_K8S_CLUSTER_PREFIX",
                    "value": "XYZ"
                  },
                  {
                    "name": "X_CSI_POWERMAX_PORTGROUPS",
                    "value": ""
                  },
                  {
                    "name": "X_CSI_POWERMAX_ARRAYS",
                    "value": ""
                  },
                  {
                    "name": "X_CSI_TRANSPORT_PROTOCOL",
                    "value": ""
                  }
                ],
                "image": "dellemc/csi-powermax:v1.2.0.000R",
                "imagePullPolicy": "IfNotPresent"
              },
              "configVersion": "v1",
              "forceUpdate": false,
              "replicas": 1,
              "sideCars": [
                {
                  "name": "snapshotter"
                }
              ],
              "snapshotClass": [
                {
                  "name": "powermax-snapclass"
                }
              ],
              "storageClass": [
                {
                  "default": true,
                  "name": "bronze",
                  "parameters": {
                    "SRP": "DEFAULT_SRP",
                    "SYMID": "000000000001",
                    "ServiceLevel": "Bronze"
                  },
                  "reclaimPolicy": "Delete"
                }
              ]
            }
          }
        },
        {
          "apiVersion": "storage.dell.com/v1",
          "kind": "CSIUnity",
          "metadata": {
            "name": "test-unity",
            "namespace": "test-unity"
          },
          "spec": {
            "driver": {
              "common": {
                "envs": [
                  {
                    "name": "X_CSI_UNITY_DEBUG",
                    "value": "true"
                  },
                  {
                    "name": "X_CSI_UNITY_ENDPOINT",
                    "value": "https://0.0.0.0"
                  },
                  {
                    "name": "X_CSI_UNITY_INSECURE",
                    "value": "true"
                  }
                ],
                "image": "dellemc/csi-unity:v1.1.0.000R",
                "imagePullPolicy": "IfNotPresent"
              },
              "configVersion": "v1",
              "replicas": 1,
              "sideCars": [
                {
                  "name": "snapshotter"
                }
              ],
              "snapshotClass": [
                {
                  "name": "test-snap",
                  "parameters": {
                    "retentionDuration": ""
                  }
                }
              ],
              "storageClass": [
                {
                  "default": true,
                  "name": "fc",
                  "parameters": {
                    "protocol": "FC",
                    "storagepool": "pool_1"
                  },
                  "reclaimPolicy": "Delete"
                },
                {
                  "name": "iscsi",
                  "parameters": {
                    "protocol": "iSCSI",
                    "storagepool": "pool_1"
                  },
                  "reclaimPolicy": "Delete"
                }
              ]
            }
          }
        },
        {
          "apiVersion": "storage.dell.com/v1",
          "kind": "CSIVXFlexOS",
          "metadata": {
            "name": "test-vxflexos",
            "namespace": "test-vxflexos"
          },
          "spec": {
            "driver": {
              "common": {
                "envs": [
                  {
                    "name": "X_CSI_VXFLEXOS_SYSTEMNAME",
                    "value": "systemname"
                  },
                  {
                    "name": "X_CSI_VXFLEXOS_ENDPOINT",
                    "value": "https://127.0.0.0"
                  },
                  {
                    "name": "X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT",
                    "value": "false"
                  },
                  {
                    "name": "X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE",
                    "value": "false"
                  },
                  {
                    "name": "X_CSI_DEBUG",
                    "value": "true"
                  }
                ],
                "image": "dellemc/csi-vxflexos:v1.1.4.000R",
                "imagePullPolicy": "IfNotPresent"
              },
              "configVersion": "v1",
              "forceUpdate": false,
              "replicas": 1,
              "sideCars": [
                {
                  "name": "snapshotter"
                },
                {
                  "args": [
                    "--volume-name-prefix=csi-vol"
                  ],
                  "image": "quay.io/k8scsi/csi-provisioner:v1.2.1",
                  "imagePullPolicy": "IfNotPresent",
                  "name": "provisioner"
                }
              ],
              "snapshotClass": [
                {
                  "name": "vxflexos-snapclass"
                }
              ],
              "storageClass": [
                {
                  "default": true,
                  "name": "vxflexos",
                  "parameters": {
                    "storagepool": "pool1"
                  },
                  "reclaimPolicy": "Delete"
                },
                {
                  "default": false,
                  "name": "vxflexos-xfs",
                  "parameters": {
                    "FsType": "xfs",
                    "storagepool": "pool2"
                  },
                  "reclaimPolicy": "Delete"
                }
              ]
            }
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Storage
    certified: "Yes"
    containerImage: dellemc/dell-csi-operator:v1.0.0
    createdAt: "2020-03-03T11:30:59Z"
    description: An operator for installing and managing CSI Drivers provided by Dell
      EMC
    repository: https://github.com/dell/dell-csi-operator
    support: Dell EMC
  name: csi-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CSIIsilon is the Schema for the csiisilons API
      displayName: CSI Isilon Driver
      kind: CSIIsilon
      name: csiisilons.storage.dell.com
      resources:
      - kind: DaemonSet
        name: isilon-node
        version: v1
      - kind: StatefulSet
        name: isilon-controller
        version: v1
      specDescriptors:
      - description: CSI Isilon
        displayName: Driver
        path: driver
      statusDescriptors:
      - description: Status of the driver instance
        displayName: DriverStatus
        path: status
      version: v1
    - description: CSIPowerMax is the Schema for the csipowermaxes API
      displayName: CSI PowerMax Driver
      kind: CSIPowerMax
      name: csipowermaxes.storage.dell.com
      resources:
      - kind: DaemonSet
        name: powermax-node
        version: v1
      - kind: StatefulSet
        name: powermax-controller
        version: v1
      specDescriptors:
      - description: CSI PowerMax
        displayName: Driver
        path: driver
      statusDescriptors:
      - description: Status of the driver instance
        displayName: DriverStatus
        path: status
      version: v1
    - description: CSIUnity is the Schema for the csiunities API
      displayName: CSI Unity Driver
      kind: CSIUnity
      name: csiunities.storage.dell.com
      resources:
      - kind: DaemonSet
        name: unity-node
        version: v1
      - kind: StatefulSet
        name: unity-controller
        version: v1
      specDescriptors:
      - description: CSI Unity
        displayName: Driver
        path: driver
      statusDescriptors:
      - description: Status of the driver instance
        displayName: DriverStatus
        path: status
      version: v1
    - description: CSIVXFlexOS is the Schema for the csivxflexoses API
      displayName: CSI VxFlexOS Driver
      kind: CSIVXFlexOS
      name: csivxflexoses.storage.dell.com
      resources:
      - kind: DaemonSet
        name: vxflexos-node
        version: v1
      - kind: StatefulSet
        name: vxflexos-controller
        version: v1
      specDescriptors:
      - description: CSI VxFlexOS
        displayName: Driver
        path: driver
      statusDescriptors:
      - description: Status of the driver instance
        displayName: DriverStatus
        path: status
      version: v1
  description: |-
    CSI Operator for Dell EMC CSI Drivers
    CSI Operator is an operator which can be used to install and manage various CSI Drivers provided by Dell EMC for different storage arrays.
  displayName: CSI Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAAEpub2lAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAB4UExURQAAAABTwABYwwBjxgBoyQB2zhF5zxqC0R5/0CKE0iSG0zKK1DOK1TqS10OW2VZWVlmg3WdnZ2mq4HWw4nd3d32044K35YiIiJPA6JfE6ZiYmJrE6qqqqqvO7bPP7ry8vL7Z8Mre88vLy9jY2Nzr+Ozy+u/v7/T5/X8DYQgAAAABdFJOUwBA5thmAAAACXBIWXMAABX9AAAV/QHNcFFhAAACEElEQVQ4T+1V0XKbQAxcQLIDOHZwSEivh7Ehwf//h1kJSJOHtpM8dCYdduYOoRN7Eifp8BvsCptDw+nHBYnUQGWav+CaYh9dElwy6cYD+OUXIUoW7DERjj7/Q+zm5wRuLxBB6k7BnApAB4XqAz1NXFkdqKQlTRSZJIK6pibAfuT3hYpF5GExLgp7Tn4s0eYu2ikPlGxR9dks1eTUDLtIq8j1EcGMDHp+0i1KvZMSempb2bXtzOjrwf7uLK/4rvCateTZAPfyE7hdMgi9Td4b2Fd4zgfqWXFyZuqc9eiGNlhiRE/zYfAWRE4z3Kggl5dfOYnG0qyzRtV78hBmmOWSCY66fTN0xol26U6an8gHyTiXcmqZn+15MawqGloqcjCWG9NmGZBn3NyDq+q6ouE4WFix+XrLW7HifwKrwwrkaX5lcacvJhRp6gok6XLNRhYRYd2AvWDGwW+AWDWhnopKtbi0LYt/y5eC3FduUvCytvI1pGpXjiF6+RpiZ43DUPXsDHHuDry2jNAduIpuROUeOPLRTv3FIX7ZGd4TjpM79UjCcWF3qNxOTxXV8plsJXBKlO+uf08Yhn7oe96JpDbPEHp0AUMzrU+YCW9ELiClHNl5RBT7P3vIwXbIEG0sf3S0TchBaJa76oE9T7NHSuW0kIDOmsCm/ZEQIZhn9JCR+8n0H0J/w+LPZ+H3xYoVnwfwCrmDHOwcvvZYAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - rolebindings
          - clusterrolebindings
          verbs:
          - get
          - list
          - watch
          - update
          - create
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - roles
          verbs:
          - get
          - list
          - watch
          - create
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - csi-operator
          resources:
          - deployments/finalizers
          - '*'
          verbs:
          - update
        - apiGroups:
          - storage.dell.com
          resources:
          - '*'
          - csipowermaxes
          - csiunities
          - csivxflexoses
          - csiisilons
          verbs:
          - '*'
        - apiGroups:
          - storage.k8s.io
          resources:
          - csidrivers
          verbs:
          - get
          - list
          - watch
          - create
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          verbs:
          - get
          - list
          - watch
          - update
          - create
        - apiGroups:
          - storage.k8s.io
          resources:
          - csinodes
          verbs:
          - get
          - list
          - watch
          - update
          - create
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotclasses
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots/status
          verbs:
          - update
          - create
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - get
          - list
          - watch
          - update
          - create
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - list
          - watch
          - delete
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: csi-operator
      deployments:
      - name: csi-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: csi-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: csi-operator
            spec:
              containers:
              - args:
                - --zap-level=debug
                - --zap-encoder=console
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: csi-operator
                - name: OPERATOR_DRIVERS
                  value: unity,powermax,isilon,vxflexos
                image: dellemc/dell-csi-operator:v1.0.0
                imagePullPolicy: IfNotPresent
                name: csi-operator
                resources: {}
                volumeMounts:
                - mountPath: /etc/config/csi-operator
                  name: config-volume
              serviceAccountName: csi-operator
              volumes:
              - configMap:
                  name: config-csi-operator
                  optional: true
                name: config-volume
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - CSI Driver
  - Unity
  - PowerMax
  - Isilon
  - VxFlexOS
  links:
  - name: Source Code
    url: https://github.com/dell/dell-csi-operator
  maintainers:
  - email: dell.csi.operator@dell.com
    name: Dell CSI Operator
  maturity: stable
  provider:
    name: Dell EMC
  version: 1.0.0
