apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: federatorai.v0.0.1
  namespace: placeholder
  annotations:
    tectonic-visibility: ocs
    capabilities: Full Lifecycle
    categories: "Database"
    alm-examples: |
      [
        {
          "apiVersion": "etcd.database.coreos.com/v1beta2",
          "kind": "EtcdCluster",
          "metadata": {
            "name": "example",
            "annotations": {
              "etcd.database.coreos.com/scope": "clusterwide"
            }
          },
          "spec": {
            "size": 3,
            "version": "3.2.13"
          }
        },
        {
          "apiVersion": "etcd.database.coreos.com/v1beta2",
          "kind": "EtcdRestore",
          "metadata": {
            "name": "example-etcd-cluster-restore",
            "annotations": {
              "etcd.database.coreos.com/scope": "clusterwide"
            }
          },
          "spec": {
            "etcdCluster": {
              "name": "example-etcd-cluster"
            },
            "backupStorageType": "S3",
            "s3": {
              "path": "<full-s3-path>",
              "awsSecret": "<aws-secret>"
            }
          }
        },
        {
          "apiVersion": "etcd.database.coreos.com/v1beta2",
          "kind": "EtcdBackup",
          "metadata": {
            "name": "example-etcd-cluster-backup",
            "annotations": {
              "etcd.database.coreos.com/scope": "clusterwide"
            }
          },
          "spec": {
            "etcdEndpoints": ["<etcd-cluster-endpoints>"],
            "storageType":"S3",
            "s3": {
              "path": "<full-s3-path>",
              "awsSecret": "<aws-secret>"
            }
          }
        }
      ]
    description: Creates and maintain highly-available etcd clusters on Kubernetes
spec:
  displayName: etcd
  description: |
    The etcd Operater creates and maintains highly-available etcd clusters on Kubernetes, allowing engineers to easily deploy and manage etcd clusters for their applications.

    etcd is a distributed key value store that provides a reliable way to store data across a cluster of machines. It’s open-source and available on GitHub. etcd gracefully handles leader elections during network partitions and will tolerate machine failure, including the leader.


    ### Reading and writing to etcd

    Communicate with etcd though its command line utility `etcdctl` via port forwarding:

        $ kubectl --namespace default port-forward service/example-client 2379:2379
        $ etcdctl --endpoints http://127.0.0.1:2379 get /

    Or directly to the API using the automatically generated Kubernetes Service:

        $ etcdctl --endpoints http://example-client.default.svc:2379 get /

    Be sure to secure your etcd cluster (see Common Configurations) before exposing it outside of the namespace or cluster.


    ### Supported Features

    * **High availability** - Multiple instances of etcd are networked together and secured. Individual failures or networking issues are transparently handled to keep your cluster up and running.

    * **Automated updates** - Rolling out a new etcd version works like all Kubernetes rolling updates. Simply declare the desired version, and the etcd service starts a safe rolling update to the new version automatically.

    * **Backups included** - Create etcd backups and restore them through the etcd Operator.

    ### Common Configurations

    * **Configure TLS** - Specify [static TLS certs](https://github.com/coreos/etcd-operator/blob/master/doc/user/cluster_tls.md) as Kubernetes secrets.

    * **Set Node Selector and Affinity** - [Spread your etcd Pods](https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#three-member-cluster-with-node-selector-and-anti-affinity-across-nodes) across Nodes and availability zones.

    * **Set Resource Limits** - [Set the Kubernetes limit and request](https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#three-member-cluster-with-resource-requirement) values for your etcd Pods.

    * **Customize Storage** - [Set a custom StorageClass](https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#custom-persistentvolumeclaim-definition) that you would like to use.
  keywords: ['etcd', 'key value', 'database', 'coreos', 'open source']
  version: 0.9.2
  maturity: alpha
  replaces: etcdoperator.v0.9.0
  maintainers:
  - name: etcd Community
    email: etcd-dev@googlegroups.com
  provider:
    name: CNCF
  labels:
    alm-owner-etcd: etcdoperator
    operated-by: etcdoperator
  selector:
    matchLabels:
      alm-owner-etcd: etcdoperator
      operated-by: etcdoperator
  links:
  - name: Blog
    url: https://coreos.com/etcd
  - name: Documentation
    url: https://coreos.com/operators/etcd/docs/latest/
  - name: etcd Operator Source Code
    url: https://github.com/coreos/etcd-operator

  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAMgAAACWCAMAAACsAjcrAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAC91BMVEUAAAD9/v3r78n09PTx8fHu7u719fX29vba2tpiZWLc3Nzf39/b4p/DxMPHx8fLy8zO13zExcTIyMjMzM3G0WjH0mrr78rIx8js8M3a29r19PXd3N329+X5+fn4+Pj6+/L5+vDs8M7s78v4+u3H0Wj///65x0T///25x0X+/f66x0b9/vy3xT7I0mvI0mrI02vU3Ir9/v3K1HHr78nCzlzM1nXM1nbX3pPL1XP09+L19fXz8/Px8fHx8fHx8fHx8fHv8O/t7e3s7Ozs7Ozy8vL9/f3+/v/r6+zm5ubm5ubm5ubw8PD+/v3f39/W1tbQ0NDf4N/x8fHKysrT09P9/f+8vL3MzM34+Pje5ajQ2YHE0GPF0GXF0GTd5KTMzcy9vr3b3Nv////x8fG5ubnu7+6UlJaurrD09PTS24i/y1S+v766urrv7++WlpiwsLH09PXL1XW1wzrM1ne2xT22xD3v8O+6ubqVlZevr7HL1XT19+TMzszc3Nzv7u/X35T19+Tg4ODW19bh4eHy8fLMzMzU09T19PW9vb7Ozs75+fj3+On19+T19+X29+X6+vr4+Pj29vb29vb29vb29vb29vb19fXz9PPz8/P09PT39/f8/Pz9/f3z8/Pw8PDw8PDw8PD29vb+/v76+/Hu8tPq7sXq7sbP2H62xD35+u/s8Mzm67zn673n7L7g5q61wzns8Mzq7sfr78n4+ezDzl22xDy3xD23xT+1wzeltg6mtxCmtxK0wzmltw+mtxGnuBOmuBOnuBXPz8/P0M++vr6/vr+/v7+qqqupqaqys7K1trWzs7OXlpeYl5iZmJl3d3l2dnivvyuwwC2wwCzR2oSztLO2t7a1tLWamZqbmpt5eXt4eHqktQultg2ktg3K1HHL1XO0wziltg+0tLS1wzjR2oPH0mnH0mrR0dHAv8DAwMCrq62rq6zBzVmtvSSuvieuviWouRa7yEi9yk+ouRepuhqpuhnN13jn7MDg5qvh5q3h5qzt8M////9HTZ/9AAAAs3RSTlMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7ArsCuwK7Av7r5+upAfIxCQsLCPEnBWZ9e3cWA2F9e2EDAVp+e31mBQvT/nxD6cgCu9MLFoaOjo6OC9O7AnXIBbvTCyfx08gFu9MLJ/En8fEFyLvT8ScLuwXDFgvThkvtyAW70wuOjpBBBnWPjogaA2+QjpBvAwFokI6PdQYCBQUFK/JY3tvb2+H9ZmZmZjqy/PcAAAABYktHRGGysEyGAAAACXBIWXMAAAGQAAABkABW8NvoAAACuklEQVR42u3cVVQUURzH8RUUA1tssVHADgxs7EbEVhQLC2ywu7s7UbC7WGRRUbAQOxCMtVuxxRefFnc8d/+Mc9T5z/H3fb73nv/nzOudqztw8JDSDhd10PHpSIheaaHFiqs9vVlHwwxKC3d0Unt6QAABBBBA1A4QQAABBBBAAAEEEEAA+Z8gx1hDQsNld9y5hNrTW4boS5YqLbcyZcupPT0BKV+hoovMKlVOofb0BKRKVSu1RwIEEFYBwi1AuAUItwDhFiDcAoRbgHCLgFi7Vqteg6hmrZSiE1PVruNWl8itXn0b0b4GDRs1JmrStFlqhZA0zVuciCBq6Z5WdKJ1K4+Tp4giW7umE+3zbBN1miiqbTtb09L07Tt07GRe5y4UJINX1zNUZ7t5CyHdz52PJrrQo2dGIaRXzEWimN4+mUxLM/fpe+myeVeuUpAsXv2uUV23BLkRfZPoVv8BWYUQ39jbRLF+A7OZltoNGhwXb96du9qEZB8yNEQytuGeViHDpBA9IIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAaBsy/G9A7hslj38Z/wTkAQ3xt/BFAmjICBryUPriWdjIUTmSIKOTgYxR9kX8x+YU7XNIBuLnQ0IePX4iadz4XKbluSdMpK40RjydJJpHl2fylMhnRM+nTssrhEx/8ZJqxkxbCjJrtqQ5c/MlnWw/b/6ChUSLFguvfdosWbpsOdGKlavyi/atXrN2HdH6DRvtKYgmA4RbgHALEG4Bwi1AuAUItwDhFiDcAuRfVCBw0+YgmXkHb+ELKbh12/YdMtu5a7eRLaTQnlev38jt7TsDW4jV3oRf/i38jQABBBBAAAEEEEAAAQQQQAABBBBAAAFEixADI0jhfe8/fFTap89qj/+zIvu/fP2msMTE7z8AofGIUB1IPooAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTktMDMtMTRUMTc6MDA6NTIrMDE6MDCjbINkAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE5LTAzLTE0VDE3OjAwOjUyKzAxOjAw0jE72AAAACB0RVh0cGRmOkhpUmVzQm91bmRpbmdCb3gANDA4eDI2NiswKzDr8x6EAAAAHXRFWHRwZGY6U3BvdENvbG9yLTAAUEFOVE9ORSA0MjEgQx6zNCoAAAAldEVYdHBkZjpTcG90Q29sb3ItMQBQQU5UT05FIENvb2wgR3JheSA3IEOzNDMdAAAAJXRFWHRwZGY6U3BvdENvbG9yLTIAUEFOVE9ORSBDb29sIEdyYXkgOSBDz08nKgAAABR0RVh0cGRmOlZlcnNpb24AUERGLTEuNQ1Ag1dMAAAAAElFTkSuQmCC
    mediatype: image/png
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: etcd-operator
        rules:
        - apiGroups:
          - etcd.database.coreos.com
          resources:
          - etcdclusters
          - etcdbackups
          - etcdrestores
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
      deployments:
      - name: etcd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: etcd-operator-alm-owned
          template:
            metadata:
              name: etcd-operator-alm-owned
              labels:
                name: etcd-operator-alm-owned
            spec:
              serviceAccountName: etcd-operator
              containers:
              - name: etcd-operator
                command:
                - etcd-operator
                - --create-crd=false
                image: quay.io/coreos/etcd-operator@sha256:c0301e4686c3ed4206e370b42de5a3bd2229b9fb4906cf85f3f30650424abec2
                env:
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              - name: etcd-backup-operator
                image: quay.io/coreos/etcd-operator@sha256:c0301e4686c3ed4206e370b42de5a3bd2229b9fb4906cf85f3f30650424abec2
                command:
                - etcd-backup-operator
                - --create-crd=false
                env:
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              - name: etcd-restore-operator
                image: quay.io/coreos/etcd-operator@sha256:c0301e4686c3ed4206e370b42de5a3bd2229b9fb4906cf85f3f30650424abec2
                command:
                - etcd-restore-operator
                - --create-crd=false
                env:
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
  customresourcedefinitions:
    owned:
    - name: etcdclusters.etcd.database.coreos.com
      version: v1beta2
      kind: EtcdCluster
      displayName: etcd Cluster
      description: Represents a cluster of etcd nodes.
      resources:
        - kind: Service
          version: v1
        - kind: Pod
          version: v1
      specDescriptors:
        - description: The desired number of member Pods for the etcd cluster.
          displayName: Size
          path: size
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        - description: Limits describes the minimum/maximum amount of compute resources required/allowed
          displayName: Resource Requirements
          path: pod.resources
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
      statusDescriptors:
        - description: The status of each of the member Pods for the etcd cluster.
          displayName: Member Status
          path: members
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:podStatuses'
        - description: The service at which the running etcd cluster can be accessed.
          displayName: Service
          path: serviceName
          x-descriptors:
            - 'urn:alm:descriptor:io.kubernetes:Service'
        - description: The current size of the etcd cluster.
          displayName: Cluster Size
          path: size
        - description: The current version of the etcd cluster.
          displayName: Current Version
          path: currentVersion
        - description: 'The target version of the etcd cluster, after upgrading.'
          displayName: Target Version
          path: targetVersion
        - description: The current status of the etcd cluster.
          displayName: Status
          path: phase
          x-descriptors:
            - 'urn:alm:descriptor:io.kubernetes.phase'
        - description: Explanation for the current status of the cluster.
          displayName: Status Details
          path: reason
          x-descriptors:
            - 'urn:alm:descriptor:io.kubernetes.phase:reason'
    - name: etcdbackups.etcd.database.coreos.com
      version: v1beta2
      kind: EtcdBackup
      displayName: etcd Backup
      description: Represents the intent to backup an etcd cluster.
      specDescriptors:
        - description: Specifies the endpoints of an etcd cluster.
          displayName: etcd Endpoint(s)
          path: etcdEndpoints
          x-descriptors: 
            - 'urn:alm:descriptor:etcd:endpoint'
        - description: The full AWS S3 path where the backup is saved.
          displayName: S3 Path
          path: s3.path
          x-descriptors: 
            - 'urn:alm:descriptor:aws:s3:path'
        - description: The name of the secret object that stores the AWS credential and config files.
          displayName: AWS Secret
          path: s3.awsSecret
          x-descriptors: 
            - 'urn:alm:descriptor:io.kubernetes:Secret'
      statusDescriptors:
        - description: Indicates if the backup was successful.
          displayName: Succeeded
          path: succeeded
          x-descriptors: 
            - 'urn:alm:descriptor:text'
        - description: Indicates the reason for any backup related failures.
          displayName: Reason
          path: reason
          x-descriptors: 
            - 'urn:alm:descriptor:io.kubernetes.phase:reason'
    - name: etcdrestores.etcd.database.coreos.com
      version: v1beta2
      kind: EtcdRestore
      displayName: etcd Restore
      description: Represents the intent to restore an etcd cluster from a backup.
      specDescriptors:
        - description: References the EtcdCluster which should be restored,
          displayName: etcd Cluster
          path: etcdCluster.name
          x-descriptors: 
            - 'urn:alm:descriptor:io.kubernetes:EtcdCluster'
            - 'urn:alm:descriptor:text'
        - description: The full AWS S3 path where the backup is saved.
          displayName: S3 Path
          path: s3.path
          x-descriptors: 
            - 'urn:alm:descriptor:aws:s3:path'
        - description: The name of the secret object that stores the AWS credential and config files.
          displayName: AWS Secret
          path: s3.awsSecret
          x-descriptors: 
            - 'urn:alm:descriptor:io.kubernetes:Secret'
      statusDescriptors:
        - description: Indicates if the restore was successful.
          displayName: Succeeded
          path: succeeded
          x-descriptors: 
            - 'urn:alm:descriptor:text'
        - description: Indicates the reason for any restore related failures.
          displayName: Reason
          path: reason
          x-descriptors: 
            - 'urn:alm:descriptor:io.kubernetes.phase:reason'
