apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: functions.ibmcloud.ibm.com
spec:
  group: ibmcloud.ibm.com
  names:
    kind: Function
    plural: functions
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            annotations:
              description: List of key/value annotations
              items:
                properties:
                  attributes:
                    description: A parameter may have attributes (e.g. message hub
                      topic might have partitions)
                    type: object
                  name:
                    description: Name representing the key.
                    type: string
                  value:
                    description: Defaults to null.
                    type: object
                  valueFrom:
                    description: Source for the value. Cannot be used if value is
                      not empty.
                    properties:
                      configMapKeyRef:
                        description: Selects a key of a ConfigMap.
                        type: object
                      secretKeyRef:
                        description: Selects a key of a secret in the resource namespace
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            code:
              description: The inline code to deploy.
              type: string
            codeURI:
              description: The location of the code to deploy. Support `http(s)` and
                `file` protocols.
              type: string
            contextFrom:
              description: 'Reference to a secret representing where to deploy this
                entity Default is `seed-default-owprops` The secret must defines these
                fields: apihost (string) : The OpenWhisk host auth (string): the authorization
                key cert (string):  the client certificate (optional) insecure (bool):  Whether
                or not to bypass certificate checking (optional, default is false)'
              type: object
            docker:
              description: 'Docker image identifier (in dockerhub). More info: https://github.com/apache/incubator-openwhisk/blob/master/docs/actions-docker.md'
              type: string
            functions:
              description: Comma separated sequence of actions. Only valid when `runtime`
                is `sequence`
              type: string
            limits:
              description: 'Sets the action limits. More info: https://github.com/apache/incubator-openwhisk/blob/master/docs/reference.md#system-limits'
              properties:
                logSize:
                  description: The action log size. Default unit is assumed to be
                    in megabytes (MB).
                  format: int64
                  type: integer
                memory:
                  description: The per-Action memory. Default unit is assumed to be
                    in megabytes (MB).
                  format: int64
                  type: integer
                timeout:
                  description: The per-invocation Action timeout. Default unit is
                    assumed to be milliseconds (ms).
                  format: int64
                  type: integer
              type: object
            main:
              description: The name of the action entry point (function or fully-qualified
                method name when applicable)
              type: string
            name:
              description: Action name. Override metadata.name. Does not include the
                package name (see below)
              type: string
            native:
              description: 'Run the action as native. More info: https://github.com/apache/incubator-openwhisk/blob/master/docs/actions-docker.md#creating-native-actions'
              type: boolean
            package:
              description: Action package name. Add it to the default package when
                not specified
              type: string
            parameters:
              description: List of key/value input parameters
              items:
                properties:
                  attributes:
                    description: A parameter may have attributes (e.g. message hub
                      topic might have partitions)
                    type: object
                  name:
                    description: Name representing the key.
                    type: string
                  value:
                    description: Defaults to null.
                    
                  valueFrom:
                    description: Source for the value. Cannot be used if value is
                      not empty.
                    properties:
                      configMapKeyRef:
                        description: Selects a key of a ConfigMap.
                        type: object
                      secretKeyRef:
                        description: Selects a key of a secret in the resource namespace
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            rawHTTP:
              description: 'Indicates if the function is able to consume the raw contents
                within the body of an HTTP request. Only valid when `webExport` is
                `true`. More info: https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md#raw-http-handling'
              type: boolean
            runtime:
              description: "Runtime name and optional version. More info: https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md#languages-and-runtimes
                \ Support these runtimes (not an exhaustive live):  Runtime\t| image
                name\t| Description\\n -------- | --------- | ----------\\n app |
                N/A | runs a function composition\\n sequence | N/A | runs a function
                sequence\\n nodejs | nodejsaction:latest | Latest NodeJS runtime\\n
                nodejs:6\t| nodejs6action:latest | Latest NodeJS 6 runtime\\n java\t|
                java8action:latest | Latest Java language runtime\\n python:2\t| python2action:latest
                | Latest Python 2 language runtime\\n python:3\t| python3action:latest
                | Latest Python 3 language runtime\\n swift | swiftaction:latest |
                Latest Swift 2 language runtime\\n swift:3\t| swift3action:latest
                | Latest Swift 3 language runtime\\n swift:3.1.1 | action-swift-v3.1.1:latest
                | Latest Swift 3.1.1 language runtime\\n php:7.1 | action-php-v7.1:latest\t|
                Latest PHP language runtime\\n"
              type: string
            webExport:
              description: 'Turns the function into a "web action" causing it to return
                HTTP content without use of an API Gateway. More info: https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md'
              type: boolean
          required:
          - runtime
          type: object
        status:
          properties:
            generation:
              description: Last synced generation. Set by the system
              format: int64
              type: integer
            message:
              type: string
            state:
              type: string
          required:
          - generation
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
