apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: invocations.ibmcloud.ibm.com
spec:
  group: ibmcloud.ibm.com
  names:
    kind: Invocation
    plural: invocations
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            contextFrom:
              description: 'Reference to a secret representing where to deploy this
                entity Default is `seed-default-owprops` The secret must defines these
                fields: apihost (string) : The OpenWhisk host auth (string): the authorization
                key cert (string):  the client certificate (optional) insecure (bool):  Whether
                or not to bypass certificate checking (optional, default is false)'
              type: object
            finalizer:
              description: Defines the function to invoke when this resource is deleted.
              properties:
                function:
                  description: Function defines the name of the function to invoke
                    (eg. `/whisk.system/utils/echo` or `myfunction`) Invokes the function
                    in the invocation context when the name is not fully qualified
                  type: string
                parameters:
                  description: Parameters defines the list of parameters to use for
                    the invocation
                  items:
                    properties:
                      attributes:
                        description: A parameter may have attributes (e.g. message
                          hub topic might have partitions)
                        type: object
                      name:
                        description: Name representing the key.
                        type: string
                      value:
                        description: Defaults to null.
                        
                      valueFrom:
                        description: Source for the value. Cannot be used if value
                          is not empty.
                        properties:
                          configMapKeyRef:
                            description: Selects a key of a ConfigMap.
                            type: object
                          secretKeyRef:
                            description: Selects a key of a secret in the resource
                              namespace
                            type: object
                        type: object
                    required:
                    - name
                    type: object
                  type: array
              required:
              - function
              type: object
            function:
              description: defines the name of function to invoke (eg. `/whisk.system/utils/echo`
                or `myfunction`) Invokes the function in the invocation context when
                the name is not fully qualified
              type: string
            parameters:
              description: Defines the list of parameters to use for the invocation
              items:
                properties:
                  attributes:
                    description: A parameter may have attributes (e.g. message hub
                      topic might have partitions)
                    type: object
                  name:
                    description: Name representing the key.
                    type: string
                  value:
                    description: Defaults to null.
                    
                  valueFrom:
                    description: Source for the value. Cannot be used if value is
                      not empty.
                    properties:
                      configMapKeyRef:
                        description: Selects a key of a ConfigMap.
                        type: object
                      secretKeyRef:
                        description: Selects a key of a secret in the resource namespace
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            to:
              description: Defines where to store the invocation result. Discard the
                result when not specified.
              properties:
                configMapKeyRef:
                  description: Selects a key of a ConfigMap.
                  type: object
                projection:
                  description: 'JSONPath template selecting parts of the invocation
                    result to store. Default is "{@.response.result}" More info: https://kubernetes.io/docs/reference/kubectl/jsonpath/'
                  type: string
                secretKeyRef:
                  description: Selects a key of a secret in the invocation namespace
                  type: object
              type: object
          required:
          - function
          type: object
        status:
          properties:
            generation:
              description: Last synced generation. Set by the system
              format: int64
              type: integer
            message:
              type: string
            state:
              type: string
          required:
          - generation
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
