apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: packages.ibmcloud.ibm.com
spec:
  group: ibmcloud.ibm.com
  names:
    kind: Package
    plural: packages
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            annotations:
              description: List of key/value annotations
              items:
                properties:
                  attributes:
                    description: A parameter may have attributes (e.g. message hub
                      topic might have partitions)
                    type: object
                  name:
                    description: Name representing the key.
                    type: string
                  value:
                    description: Defaults to null.
                    
                  valueFrom:
                    description: Source for the value. Cannot be used if value is
                      not empty.
                    properties:
                      configMapKeyRef:
                        description: Selects a key of a ConfigMap.
                        type: object
                      secretKeyRef:
                        description: Selects a key of a secret in the resource namespace
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            bind:
              description: Name of the package for which a binding should be created
              type: string
            contextFrom:
              description: 'Reference to a secret representing where to deploy this
                entity Default is `seed-default-owprops` The secret must defines these
                fields: apihost (string) : The OpenWhisk host auth (string): the authorization
                key cert (string):  the client certificate (optional) insecure (bool):  Whether
                or not to bypass certificate checking (optional, default is false)'
              type: object
            name:
              description: Package name. Override metadata.name. `default` is reserved.
              type: string
            parameters:
              description: List of key/value input parameters
              items:
                properties:
                  attributes:
                    description: A parameter may have attributes (e.g. message hub
                      topic might have partitions)
                    type: object
                  name:
                    description: Name representing the key.
                    type: string
                  value:
                    description: Defaults to null.
                    type: object
                  valueFrom:
                    description: Source for the value. Cannot be used if value is
                      not empty.
                    properties:
                      configMapKeyRef:
                        description: Selects a key of a ConfigMap.
                        type: object
                      secretKeyRef:
                        description: Selects a key of a secret in the resource namespace
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            parametersFrom:
              description: List of key/value input parameters coming from a Secret
                or ConfigMap When multiple sources are specified, all key/value pairs
                are merged into a single set of key/value pairs, from the first source
                to the last source Duplicates are handled by overriding the previous
                key/value pair. The parameters property is applied last
              items:
                properties:
                  configMapKeyRef:
                    description: Selects a key of a ConfigMap.
                    properties:
                      name:
                        description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                          TODO: Add other useful fields. apiVersion, kind, uid?'
                        type: string
                    type: object
                  secretKeyRef:
                    description: Selects a key of a secret in the resource namespace
                    properties:
                      name:
                        description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                          TODO: Add other useful fields. apiVersion, kind, uid?'
                        type: string
                    type: object
                type: object
              type: array
            publish:
              description: Package visibility; `true` for `shared`, `false` for `private`
              type: boolean
            service:
              description: indicates a cloud service resource which you want to bind
                to. This feature provides automatic injection of service keys into
                the binding parameters (for example user, password, urls)
              type: string
          type: object
        status:
          properties:
            generation:
              description: Last synced generation. Set by the system
              format: int64
              type: integer
            message:
              type: string
            state:
              type: string
          required:
          - generation
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
