apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: rules.ibmcloud.ibm.com
spec:
  group: ibmcloud.ibm.com
  names:
    kind: Rule
    plural: rules
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            contextFrom:
              description: 'Reference to a secret representing where to deploy this
                entity Default is `seed-default-owprops` The secret must defines these
                fields: apihost (string) : The OpenWhisk host auth (string): the authorization
                key cert (string):  the client certificate (optional) insecure (bool):  Whether
                or not to bypass certificate checking (optional, default is false)'
              type: object
            function:
              description: Name of the action the rule applies to
              type: string
            name:
              description: Rule name. Override metadata.name.
              type: string
            trigger:
              description: Name of the trigger the Rule applies to
              type: string
          required:
          - trigger
          - function
          type: object
        status:
          properties:
            generation:
              description: Last synced generation. Set by the system
              format: int64
              type: integer
            message:
              type: string
            state:
              type: string
          required:
          - generation
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
