name: Prepare Test Index
env:
  GODEBUG: x509ignoreCN=0
  
on:
  repository_dispatch:
    types:
      - manual-test-index
      - index-for-openshift-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build temp index and push
        env:
          # CONTAINER_TOOL: podman
          OP_DEBUG: 0
          OP_TOKEN: ${{ secrets.QUAY_API_TOKEN_OPERATOR_TESTING }}
          OPRT_SCRIPT: https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/osr_run.sh
          OP_PR: ${{ github.event.client_payload.source_pr }}
        run: |
          echo ${{ github.event.client_payload.source_pr }} >> file
          echo
          echo
          echo -n "Preparing temp index for PR: "
          cat file
          echo
          echo
          bash <(curl -sL https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/oprt.sh)

